name: Shoption CallTracker CI/CD

on:
  push:
    branches:
      - test
      - production

jobs:

  deploy-testing:
    name: Deploy to Testing Slot
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy to Testing
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TESTING }}
          slot-name: testing
          package: ./server

  deploy-production:
    name: Deploy to Production Slot
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy to Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PROD }}
          package: ./server
